Menambahkan anime Sword Art Online
ardianta/anime-for-dev pull request #14
Opened 2020-10-10 11:59 UTC by ianoit

- **Title**: 
- **Link**: 

**Why this anime should watched by developer?**

2020-10-12 09:48 UTC, ardianta requested changes
Add the anime to `README.md` file

2020-10-12 09:48 UTC, ardianta commented on Sword_Art_Online.md
> +- **Title**: Sword Art Online
Please add to the `README.md` file

2020-10-12 15:22 UTC, AdamArthurF commented on Sword_Art_Online.md
> +- **Title**: Sword Art Online
Wkwk santuy bang

2020-10-13 11:19 UTC, ianoit commented on Sword_Art_Online.md
> +- **Title**: Sword Art Online
done bang

2020-10-14 05:54 UTC, ardianta approved these changes

2020-10-14 05:55 UTC, ardianta commented on Sword_Art_Online.md
> +- **Title**: Sword Art Online
Siap, thank you

2020-10-14 05:55 UTC, merged